EDU.Web/Models/BaseVM.cs
namespace EDU.Web.Models
{
    public class BaseVM
    {
        public int Id { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}

EDU.Web/Models/CustomResponseVM.cs
namespace EDU.Web.Models
{
    public class CustomResponseVM<T> where T : class
    {
        public T Data { get; set; }
        public List<string> Errors { get; set; }
        public int StatusCode { get; set; }
    }
}

EDU.Web/Models/UserViewModels/LoginVM.cs
namespace EDU.Web.Models.UserViewModels
{
    public class LoginVM
    {
        public string EMail { get; set; }
        public string Password { get; set; }
    }
}

EDU.Web/Models/UserViewModels/MenuItemVM.cs
namespace EDU.Web.Models.UserViewModels
{
    public class MenuItemVM : BaseVM
    {
        public string Name { get; set; }
        public string Url { get; set; }
        public string IconPath { get; set; }
        public int RowNumber { get; set; }
    }
}

EDU.Web/Models/UserViewModels/UserVM.cs
namespace EDU.Web.Models.UserViewModels
{
    public class UserVM : BaseVM
    {
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public int RoleId { get; set; }
    }
}

EDU.Web/Controllers/AccountController.cs
using EDU.Web.Models.UserViewModels;
using EDU.Web.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.Json;

namespace EDU.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserApiService _userApiService;

        public AccountController(UserApiService userApiService)
        {
            _userApiService = userApiService;
        }

        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogIn(LoginVM login)
        {
            var response = await _userApiService.LoginAsync(login);
            if (response != null)
            {
                ClaimsIdentity claims = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                claims.AddClaim(new Claim(ClaimTypes.Role, response.Role));
                var principal = new ClaimsPrincipal(claims);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                HttpContext.Session.SetString("CurrentUser", JsonSerializer.Serialize(response));
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public async Task<IActionResult> AccessDenied()
        {
            return View();
        }

        public async Task<IActionResult> LogOut()
        {
            HttpContext.Session.Clear();
            await HttpContext.SignOutAsync();
            return RedirectToAction("LogIn");
        }
    }
}

EDU.Web/Controllers/AdvertController.cs
using Microsoft.AspNetCore.Mvc;

namespace EDU.Web.Controllers
{
    public class AdvertController : Controller
    {
        public IActionResult Al()
        {
            return View();
        }
    }
}

EDU.Web/Controllers/ClassroomController.cs
using EDU.Web.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EDU.Web.Controllers
{
    [SessionFilter]
    [Authorize(Roles = "Teacher,Supervisor")]
    public class ClassroomController : Controller
    {
        public IActionResult All()
        {
            return View();
        }

        public IActionResult MyClassrooms()
        {
            return View();
        }

        public IActionResult Detail(int id)
        {
            return View(id);
        }
    }
}

EDU.Web/Controllers/EducationController.cs
using Microsoft.AspNetCore.Mvc;

namespace EDU.Web.Controllers
{
    public class EducationController : Controller
    {
        public IActionResult All()
        {
            return View();
        }
    }
}

EDU.Web/Controllers/HomeController.cs
using EDU.Web.Filters;
using EDU.Web.Models.UserViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace EDU.Web.Controllers
{
    [SessionFilter]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var response = JsonSerializer.Deserialize<UserVM>(HttpContext.Session.GetString("CurrentUser"));
            return View(response);
        }
    }
}

EDU.Web/Controllers/LessonController.cs
using Microsoft.AspNetCore.Mvc;

namespace EDU.Web.Controllers
{
    public class LessonController : Controller
    {
        public IActionResult All()
        {
            return View();
        }
    }
}

EDU.Web/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;

namespace EDU.Web.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult All()
        {
            return View();
        }
    }
}

EDU.Web/Controllers/UserController.cs
using EDU.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace EDU.Web.Controllers
{
    [SessionFilter]
    public class UserController : Controller
    {
        public IActionResult All()
        {
            return View();
        }

        public IActionResult AllStudents()
        {
            return View();
        }

        public IActionResult AllTeachers()
        { 
            return View();
        }
}
}

EDU.Web/ViewComponents/MenuViewComponent.cs
using EDU.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace EDU.Web.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly UserApiService _userApiService;
        public MenuViewComponent(UserApiService userApiService)
        {
            _userApiService = userApiService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int roleId)
        {
            return View("_MenuPartial", await _userApiService.GetMenuItemAsync(roleId));
        }
    }
}

EDU.Web/Views/Advert/All.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

EDU.Web/Views/Classroom/All.cshtml
@section endBodyArea{
<script src="~/assets/js/ClassroomScript/ClassroomScript.js" type="text/javascript"> </script>
<script src="~/assets/js/CustomScript.js" type="text/javascript"> </script>
}

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Tüm Sınıflar </h4>
        <button type="button" class="btn btn-primary" onclick="insertClassroomOpenModal()">+ Yeni Sınıf</button>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="classroomDT" class="display dataTable" style="width:100%;">
                <thead>
                    <tr>
                        <th>Sınıf Adı</th>
                        <th>Eğitim Adı</th>
                        <th>Oluşturulma Tarihi</th>
                        <th>İşlemler</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

@await Html.PartialAsync("../Shared/PartialViews/_AddClassroomModalPartial")

<!-- Include Student Modal -->
<div id="includeStudentModal" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Sınıfa Öğrenci Ata</h5>
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
            </div>
            <form class="form-valide" id="includeStudentForm">
                <div class="modal-body">
                    <div class="form-validation">
                        <div class="row">
                            <div class="col-xl-8">
                                <div class="form-group row">
                                    <label class="col-lg-6 col-form-label" for="studentDropDown">
                                        Öğrenci Seçiniz:
                                        <span class="text-danger">*</span>
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="hidden" name="hiddenClassroomId" id="hiddenClassroomId" />
                                        <select class="form-control" id="studentId" name="studentId" required>
                                            <option value="" selected disabled>Öğrenci Seçiniz..</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Ekle</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Show Student Modal -->
<div id="showStudentModal" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Sınıfın Öğrencileri</h5>
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table id="studentDT" class="display dataTable" style="width:100%;">
                        <thead>
                            <tr>
                                <th>Kullanıcı Adı</th>
                                <th>Adı</th>
                                <th>Soyadı</th>
                                <th>e-Posta</th>
                                <th>Parola</th>
                                <th>Üyelik Tarihi</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="close" data-dismiss="modal">Kapat</button>
            </div>
        </div>
    </div>
</div>

EDU.Web/Views/Classroom/Detail.cshtml
@model int
@section endBodyArea{
<script src="~/assets/js/ClassroomScript/ClassroomScript.js" type="text/javascript"> </script>
<script>
    GetDetailByClassroomId(@Model);
    GetActivitiesByClassroomId(@Model);
</script>
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Sınıf Kartı</h2>
            </div>
            <div class="card-body pb-0">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex px-0 justify-content-between">
                        <strong>Sınıf Adı</strong>
                        <span id="classroomName" class="mb-0"></span>
                    </li>
                    <li class="list-group-item d-flex px-0 justify-content-between">
                        <strong>Eğitmen</strong>
                        <span id="teacherName" class="mb-0"></span>
                    </li>
                    <li class="list-group-item d-flex px-0 justify-content-between">
                        <strong>Eğitim</strong>
                        <span id="educationName" class="mb-0"></span>
                    </li>
                    <li class="list-group-item d-flex px-0 justify-content-between">
                        <strong>Başlangıç Tarihi</strong>
                        <span id="createdOn" class="mb-0"></span>
                    </li>
                </ul>
            </div>
            <div class="card-footer pt-0 pb-0 text-center">
                <div class="row">
                    <div class="col-6 pt-3 pb-3 border-right">
                        <h3 id="studentCount" class="mb-1 text-primary"></h3>
                        <span>Öğrenci</span>
                    </div>
                    <div class="col-6 pt-3 pb-3 border-right">
                        <h3 id="activityCount" class="mb-1 text-primary"></h3>
                        <span>Aktivite</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-block">
                <div class="row">
                    <div class="col-md-3" style="align-self: center;">
                        <h4 class="card-title">Sınıfın Aktiviteleri</h4>
                    </div>
                    <div class="col-md-7">
                    </div>
                    <div class="col-md-2" style="left: 5.3%;">
                        <button class="btn btn-primary" onclick="showInsertActivityModal();">Aktivite Gir</button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div id="activityListAccordion" class="accordion">
                    <!-- Js ile doldurulacak.. -->
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Insert Aktivity Modal -->
<div id="insertActivityModal" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Yeni Aktivite Oluştur</h5>
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
            </div>
            <form class="form-valide" id="insertActivityForm">
                <div class="modal-body">
                    <div class="form-validation">
                        <div class="row">
                            <div class="col-xl-12">
                                <input type="hidden" value="@Model" id="classroomId" />
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label" for="studentDropDown">
                                        Ders Seçiniz:
                                        <span class="text-danger">*</span>
                                    </label>
                                    <div class="col-lg-9">
                                        <select class="form-control" id="lessonId" name="lessonId" required>
                                            <option value="" selected disabled>Ders Seçiniz..</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label" for="val-firstname">
                                        Tarih:
                                        <span class="text-danger">*</span>
                                    </label>
                                    <div class="col-lg-9">
                                        <input type="datetime-local" class="form-control" id="val-activityDate" name="val-activityDate">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label" for="val-firstname">
                                        Ders İçeriği:
                                        <span class="text-danger">*</span>
                                    </label>
                                    <div class="col-lg-9">
                                        <textarea type="text" class="form-control" id="val-activityContent" name="val-activityContent" rows="3"> </textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Ekle</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Show Inspection Modal -->
<div id="showInspectionModal" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Yoklama Al</h5>
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="form-validation">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="basic-list-group">
                                <ul class="list-group" id="studentList">
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="saveInspections()" class="btn btn-primary">Ekle</button>
            </div>
        </div>
    </div>
</div>

EDU.Web/Views/Classroom/MyClassrooms.cshtml
@section endBodyArea{
<script src="~/assets/js/ClassroomScript/ClassroomScript.js" type="text/javascript"> </script>
<script> getClassroomByTeacherId();</script>
}

<button type="button" class="btn btn-primary" onclick="insertClassroomOpenModal()">+ Yeni Sınıf</button>
<div class="row" id="teachersClassrooms">
</div>

@await Html.PartialAsync("../Shared/PartialViews/_AddClassroomModalPartial")

EDU.Web/Views/Shared/_Layout.cshtml
@{
    var currentUser = JsonSerializer.Deserialize<UserVM>(Context.Session.GetString("CurrentUser"));
}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <meta name="robots" content="" />
    <meta name="description" content="Edumin - Bootstrap Admin Dashboard" />
    <meta property="og:title" content="Edumin - Bootstrap Admin Dashboard" />
    <meta property="og:description" content="Edumin - Bootstrap Admin Dashboard" />
    <meta property="og:image" content="https://edumin.dexignlab.com/xhtml/social-image.png" />
    <meta name="format-detection" content="telephone=no">

    <!-- FAVICONS ICON -->
    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" type="image/x-icon" href="images/favicon.png" />

    <!-- PAGE TITLE HERE -->
    <title>Edumin - Bootstrap Admin Dashboard</title>

    <!-- MOBILE SPECIFIC -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- STYLESHEETS -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet">
    @* <link rel="stylesheet" href="~/vendor/select2/css/select2.min.css"> *@
    <script>
        // var baseApiUrl = "https://lms-customer-api.azurewebsites.net/api/";
        var baseApiUrl = "https://localhost:7263/api/";
        var sessionUserId = @currentUser.Id;
    </script>

</head>
<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <a href="/Home/Index" class="brand-logo">
                <img class="logo-abbr" src="~/images/logo-white.png" alt="">
                <img class="logo-compact" src="~/images/logo-text-white.png" alt="">
                <img class="brand-title" src="~/images/logo-text-white.png" alt="">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->
        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="header-left">
                            <div class="search_bar dropdown">
                                <span class="search_icon p-3 c-pointer" data-toggle="dropdown">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                                <div class="dropdown-menu p-0 m-0">
                                    <form>
                                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                                    </form>
                                </div>
                            </div>
                        </div>

                        <ul class="navbar-nav header-right">
                            <li class="nav-item dropdown notification_dropdown">
                                <a class="nav-link bell ai-icon" href="#" role="button" data-toggle="dropdown">
                                    <svg id="icon-user" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell">
                                        <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path>
                                        <path d="M13.73 21a2 2 0 0 1-3.46 0"></path>
                                    </svg>
                                    <div class="pulse-css"></div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <ul class="list-unstyled">
                                        <li class="media dropdown-item">
                                            <span class="success"><i class="ti-user"></i></span>
                                            <div class="media-body">
                                                <a href="#">
                                                    <p>
                                                        <strong>Martin</strong> has added a <strong>customer</strong> Successfully
                                                    </p>
                                                </a>
                                            </div>
                                            <span class="notify-time">3:20 am</span>
                                        </li>
                                        <li class="media dropdown-item">
                                            <span class="primary"><i class="ti-shopping-cart"></i></span>
                                            <div class="media-body">
                                                <a href="#">
                                                    <p><strong>Jennifer</strong> purchased Light Dashboard 2.0.</p>
                                                </a>
                                            </div>
                                            <span class="notify-time">3:20 am</span>
                                        </li>
                                        <li class="media dropdown-item">
                                            <span class="danger"><i class="ti-bookmark"></i></span>
                                            <div class="media-body">
                                                <a href="#">
                                                    <p>
                                                        <strong>Robin</strong> marked a <strong>ticket</strong> as unsolved.
                                                    </p>
                                                </a>
                                            </div>
                                            <span class="notify-time">3:20 am</span>
                                        </li>
                                        <li class="media dropdown-item">
                                            <span class="primary"><i class="ti-heart"></i></span>
                                            <div class="media-body">
                                                <a href="#">
                                                    <p><strong>David</strong> purchased Light Dashboard 1.0.</p>
                                                </a>
                                            </div>
                                            <span class="notify-time">3:20 am</span>
                                        </li>
                                        <li class="media dropdown-item">
                                            <span class="success"><i class="ti-image"></i></span>
                                            <div class="media-body">
                                                <a href="#">
                                                    <p>
                                                        <strong> James.</strong> has added a<strong>customer</strong> Successfully
                                                    </p>
                                                </a>
                                            </div>
                                            <span class="notify-time">3:20 am</span>
                                        </li>
                                    </ul>
                                    <a class="all-notification" href="#">
                                        See all notifications <i class="ti-arrow-right"></i>
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item dropdown header-profile">
                                <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                                    <img src="~/images/profile/pic1.jpg" width="20" alt="" />
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="./app-profile.html" class="dropdown-item ai-icon">
                                        <svg id="icon-user1" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                        <span class="ml-2">Profile </span>
                                    </a>
                                    <a href="./email-inbox.html" class="dropdown-item ai-icon">
                                        <svg id="icon-inbox" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                                        <span class="ml-2">Inbox </span>
                                    </a>
                                    <a href="/Account/LogOut" class="dropdown-item ai-icon">
                                        <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
                                        <span class="ml-2">Logout </span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->
        @await Component.InvokeAsync("Menu", currentUser.RoleId)
        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright © Designed &amp; Developed by <a href="http://dexignlab.com/" target="_blank">DexignLab</a> 2021</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->
    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
    <script src="~/vendor/global/global.min.js"></script>
    <script src="~/js/custom.min.js"></script>
    <script src="~/js/dlabnav-init.js"></script>

    <script src="~/vendor/highlightjs/highlight.pack.min.js"></script>

    <!-- Svganimation scripts -->
    <script src="~/vendor/svganimation/vivus.min.js"></script>
    <script src="~/vendor/svganimation/svg.animation.js"></script>

    <!-- Datatable -->
    <script src="~/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/js/plugins-init/datatables.init.js"></script>

    <!-- Sweetalert -->
    <script src="~/vendor/sweetalert2/dist/sweetalert2.min.js"></script>
    @*<script src="~/js/plugins-init/sweetalert.init.js"></script>*@

    @*    <script src="~/vendor/select2/js/select2.full.min.js"></script>
        <script src="~/js/plugins-init/select2-init.js"></script>*@

    <!-- Only Page Scripts -->
    @RenderSection("endBodyArea",false);


</body>
</html>